### ISSUE TITLE
Eclipse not working

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [ferreusveritas/ExampleTrees#1]
I used "gradlew setupDecompWorkspace eclipse" but there is no eclipse folder to set a workspace to.
what am i doing wrong?

**Comment by ghost** [comment]
Run "gradlew setupDecompWorkspace" then run "gradlew eclipse"

**Comment by ErdbeerbaerLP** [comment]
Already tried

**Comment by ghost** [comment]
The structure of the mod is pretty standard.  So you shouldn't have a problem with it.  May I ask what your experience level with setting up projects and modding in general is?

**Comment by ErdbeerbaerLP** [comment]
I already created my own mod. (but need more content)

http://erdbeerbaer.tk/trollmod/ if you are interested

**Comment by ghost** [comment]
Have you ever built someone else's mod project that you got from github?

**Comment by ErdbeerbaerLP** [comment]
Not really

**Comment by ErdbeerbaerLP** [comment]
I tried to update an mod but failed at it because of way too many errors

**Comment by ghost** [comment]
Can you send me the error output of the console when you run the gradle script?

**Comment by ErdbeerbaerLP** [comment]
Did not throw an error...
<details>
  <summary>Click to expand</summary>

```
>gradlew setupDecompWorkspace eclipse
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html.
Download http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/2.3-SNAPSHOT/ForgeGradle-2.3-20180422.205022-29.jar
This mapping 'snapshot_20171003' was designed for MC 1.12! Use at your own peril.
#################################################
         ForgeGradle 2.3-SNAPSHOT-4a7d623
  https://github.com/MinecraftForge/ForgeGradle
#################################################
                 Powered by MCP
             http://modcoderpack.com
     by: Searge, ProfMobius, R4wk, ZeuX
     Fesh0r, IngisKahn, bspkrs, LexManos
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:deobfMcSRG SKIPPED
:decompileMc SKIPPED
:fixMcSources SKIPPED
:applySourcePatches
:remapMcSources SKIPPED
:recompileMc SKIPPED
:extractNatives SKIPPED
:getAssetIndex UP-TO-DATE
:getAssets
Current status: 282/1283   21%
Current status: 663/1283   51%
Current status: 1030/1283   80%
:makeStart
:setupDecompWorkspace
:eclipseClasspath
:eclipseJdt
:eclipseProject
:makeEclipseCleanRunClient UP-TO-DATE
:makeEclipseCleanRunServer UP-TO-DATE
:eclipse

BUILD SUCCESSFUL

Total time: 1 mins 36.737 secs
```
</details>

**Comment by ghost** [comment]
So now you just open eclipse and add the project.

**Comment by ErdbeerbaerLP** [comment]
there is no generated eclipse folder
![image](https://user-images.githubusercontent.com/27149563/39197436-bf5d2a52-47e4-11e8-9c7b-b3d9a691b4fe.png)

**Comment by ghost** [comment]
There is no eclipse folder.  the ".project" is the eclipse project.

**Comment by ErdbeerbaerLP** [comment]
oh. when that was changed?

**Comment by ghost** [comment]
No idea.  Either it was a long while ago or never was that way.  I just looked in my projects for 1.7.10, 1.10.2, 1.11.2 and none of them have an eclipse folder despite being loaded happily as projects into my eclipse IDE.

**Comment by ErdbeerbaerLP** [comment]
While modding i always had an eclipse folder to open as workspace
